liaopping/therapist_matching

app/assets/javascripts/users.coffee, app/assets/stylesheets/users.scss, app/controllers/users_controller.rb, app/helpers/users_helper.rb, app/views/users/show.html.erb, config/routes.rb, db/migrate/20200830083700_insert_initial_users.rb, db/schema.rb, test/controllers/users_controller_test.rb
=> [Add]user_show_method_#3

app/helpers/users_helper.rb, app/views/users/show.html.erb
=> [add]user_show_display_image_#5

db/migrate/20200830013855_create_users.rb, db/migrate/20200830083700_insert_initial_users.rb, db/schema.rb
=> [modify]pref_data_to_users_#8

Dockerfile, Gemfile, Gemfile.lock, app/models/user.rb, app/uploaders/image_uploader.rb, app/views/users/new.html.erb
=> [modify]user_signup_add_image_uploader_#11

.gitignore, Gemfile, Gemfile.lock, config/initializers/carrierwave.rb
=> [add]introduce_dotenv_#17

Gemfile, Gemfile.lock, app/models/user.rb, db/migrate/20200830013855_create_users.rb, db/schema.rb
=> [Add]gem_bcrypt追加, usersテーブル_パスワードカラム名変更, User.rb_has_secure_password追記

app/assets/javascripts/sessions.coffee, app/assets/stylesheets/sessions.scss, app/controllers/sessions_controller.rb, app/helpers/sessions_helper.rb, app/views/sessions/new.html.erb, config/routes.rb, test/controllers/sessions_controller_test.rb
close #37 
参考: https://qiita.com/d0ne1s/items/7c4d2be3f53e34a9dec7
=> [Add]セッションコントローラー生成&ルーティング設定

app/views/sessions/new.html.erb, docker-compose.yml
close #23 
[https://note.com/hikkymouse_pro/n/n9a836181f9d4](url)
- webコンテナをビルド時にプロセスidをkillするよう追記
[https://qiita.com/paranishian/items/862ce4de104992df48e1](url)
=> [Add]ログインフォーム作成&docker-compose.yml修正_#23

app/models/customer.rb, db/migrate/20200916055408_create_customers.rb, db/schema.rb, test/fixtures/customers.yml, test/models/customer_test.rb
close #43 
- Customerモデル作成
- migrationファイル作成（追加予定の外部キーについてコメントを残した。）
- migrate実行
=> [Add]Customerモデル作成&migrate実行_#43

app/helpers/customers_helper.rb, app/views/customers/show.html.erb
=> [Add]カスタマーヘルパーメソッド定義・ビューでの呼び出し_#5

Gemfile, Gemfile.lock, config/application.rb, config/locales/customers/ja.yml, config/locales/model.ja.yml
=> [Add]i18nによるサインアップフォームの日本語化_#49

app/models/customer.rb, app/views/customers/new.html.erb
=> [Add]カスタマーサインアップに画像アップ項目追加_#11

Gemfile, Gemfile.lock, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml
=> [Add]deviseインストール・development.rbメール設定追記_#52

app/views/layouts/application.html.erb
=> [Add]ログイン時のフラッシュメッセージ表示_#56

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
=> [Add]deviseのviewを生成_#58

app/controllers/therapists/confirmations_controller.rb, app/controllers/therapists/omniauth_callbacks_controller.rb, app/controllers/therapists/passwords_controller.rb, app/controllers/therapists/registrations_controller.rb, app/controllers/therapists/sessions_controller.rb, app/controllers/therapists/unlocks_controller.rb, config/routes.rb
close #28 
ブランチ名はindexアクションも定義するつもりの書き方をしたが、今回のコミットには含めない(作業していない)。
=> [Add]deviseでTherapistモデルに対応したコントローラを生成・ルーティングにdevise_forアクション追記_#28

app/assets/javascripts/pages.coffee, app/assets/stylesheets/pages.scss, app/controllers/pages_controller.rb, app/helpers/pages_helper.rb, app/views/pages/top.html.erb, config/routes.rb, test/controllers/pages_controller_test.rb
=> [Add]pagesコントローラ生成・topアクション定義_#66

app/views/pages/top.html.erb
close #68 
Customerモデルにサインアップ時メール認証を要求するモジュール(confirmable)、を追加していたが必要なカラムやサーバーの設定をしていなかったためメールを飛ばせず。
結果的に本issueの画面切り替えの挙動も確認できなかったためメール認証を実装するissueを立てることとする。
=> [Modify]Topページのviewをログイン時と未ログイン時で切り替え_#68

app/controllers/customers_controller.rb, app/views/customers/confirmations/new.html.erb, app/views/customers/mailer/confirmation_instructions.html.erb, app/views/customers/mailer/email_changed.html.erb, app/views/customers/mailer/password_change.html.erb, app/views/customers/mailer/reset_password_instructions.html.erb, app/views/customers/mailer/unlock_instructions.html.erb, app/views/customers/passwords/edit.html.erb, app/views/customers/passwords/new.html.erb, app/views/customers/registrations/edit.html.erb, app/views/customers/registrations/new.html.erb, app/views/customers/sessions/new.html.erb, app/views/customers/shared/_error_messages.html.erb, app/views/customers/shared/_links.html.erb, app/views/customers/unlocks/new.html.erb
=> [Add]deviseでカスタマーのviewを生成_#72

app/views/pages/top.html.erb
=> [Add]Topページにセラピストログイン・サインアップのリンクを追加_#74

app/assets/javascripts/therapists.coffee, app/assets/stylesheets/therapists.scss, app/controllers/therapists_controller.rb, app/helpers/therapists_helper.rb, app/views/therapists/index.html.erb, config/routes.rb, test/controllers/therapists_controller_test.rb
=> [Add]therapists_controller生成・indexアクション定義_#76

app/views/therapists/index.html.erb
=> [Add]セラピスト一覧ページでセラピスト画像を表示_#80
